# Generated by Django 4.2.5 on 2023-10-25 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512, verbose_name='Question')),
                ('answer_1', models.CharField(max_length=128, verbose_name='Answer_1')),
                ('answer_2', models.CharField(max_length=128, verbose_name='Answer_2')),
                ('answer_3', models.CharField(max_length=128, verbose_name='Answer_3')),
                ('answer_4', models.CharField(max_length=128, verbose_name='Answer_4')),
                ('answer_right', models.IntegerField()),
                ('notes', models.CharField(max_length=128, verbose_name='Notes')),
                ('picyure', models.CharField(max_length=256, verbose_name='Image')),
            ],
        ),
    ]
