# Generated by Django 4.2.5 on 2023-10-25 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='picyure',
            new_name='picture',
        ),
    ]
