# Generated by Django 4.2.5 on 2023-11-08 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_rename_picyure_questions_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='answer_right',
            field=models.IntegerField(verbose_name='Right answer'),
        ),
    ]
