# Generated by Django 4.2.5 on 2023-11-08 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_questions_answer_right'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='picture',
            field=models.TextField(verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='title',
            field=models.TextField(verbose_name='Question'),
        ),
    ]
