# Generated by Django 4.2.5 on 2024-01-17 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='answer_r',
            field=models.IntegerField(verbose_name='answer_r'),
        ),
    ]
