# Generated by Django 4.2.5 on 2024-01-30 08:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_questions_answer_r'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questions',
            options={},
        ),
        migrations.AlterModelOptions(
            name='quizzes',
            options={},
        ),
        migrations.AlterField(
            model_name='questions',
            name='answer_r',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
    ]
